---
- name: Deploiement
  hosts: 46.226.105.161

  tasks:
    - name: Synchronize data from local to server
      synchronize:
        src: /home/jeremie/Code/lespressesdurl.net
        dest: /home/debian/lespressesdurl.net
        delete: yes
        rsync_path: "sudo rsync"
        recursive: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"
    # - name: Docker down
    #   shell: 
    #     cmd: "docker stop lespressesdurl.net"
    - name: Docker build
      shell:
        cmd: "docker build -t lespressesdurl_app ."
        chdir: /home/debian/lespressesdurl.net
    - name: Docker up
      shell:
        cmd: "docker run --name lespressesdurl.net -d -it -p 3000:3000 lespressesdurl_app"
        chdir: /home/debian/lespressesdurl.net
